using System;
using System.Buffers;
using System.Diagnostics;
using System.Text;

namespace Yoh.Text.Segmentation
{
    public static class StringExtensions
    {
        public static WordEnumerator EnumerateWords(this string source) =>
            new WordEnumerator(source);

        public static WordEnumerator EnumerateWords(this Span<char> source) =>
            new WordEnumerator(source);

        public static WordEnumerator EnumerateWords(this ReadOnlySpan<char> source) =>
            new WordEnumerator(source);

        public ref struct WordEnumerator
        {
            private ReadOnlySpan<char> _source;
            private ReadOnlySpan<char> _current;
            private RuneInfo _currentRune;
            private int _currentIndex;

            internal WordEnumerator(ReadOnlySpan<char> source)
            {
                _source = source;
                _current = default;
                _currentRune = default;
                _currentIndex = default;
            }

            public ReadOnlySpan<char> Current => _current;

            public WordEnumerator GetEnumerator() => this;

            public bool MoveNext()
            {
                if ((uint)_currentIndex >= _source.Length)
                {
                    _current = default;
                    return false;
                }

                var state = State.Start;
                var savedRune = default(RuneInfo);
                int savedIndex = default;
                int startIndex = _currentIndex;

                var handleFormatExtend = true;
                const State BreakMask = State.BreakConsumeLast | State.BreakConsumeNone;
                const State StateMask = ~BreakMask;

                while (_currentIndex < _source.Length)
                {
                    var previousCategory = _currentRune.Category;

                    var rune = _currentRune;
                    if (rune.Category == RuneCategory.None)
                    {
                        TryDecodeRune(_source, out _currentRune);
                    }

                    if (state != State.Start)
                    {
                        if (rune.Category == RuneCategory.Extend ||
                            rune.Category == RuneCategory.Format ||
                            rune.Category == RuneCategory.Zwj)
                        {
                            handleFormatExtend = false;
                            continue;
                        }
                    }

                    if (previousCategory == RuneCategory.Zwj)
                    {
                        // is emoji
                        state = State.Emoji;
                        continue;
                    }

                    state = state switch
                    {
                        State.Start => rune.Category switch
                        {
                            RuneCategory.ALetter => State.AHLetter,
                            RuneCategory.HLetter => State.HLetter,
                            RuneCategory.Numeric => State.Numeric,
                            RuneCategory.Katakana => State.Katakana,
                            RuneCategory.ExtendNumLet => State.ExtendNumLet,
                            RuneCategory.RegionalIndicator => State.RegionalIndicatorHalf,
                            RuneCategory.Zwj => State.Zwj,
                            RuneCategory.WSegSpace => State.WSegSpace,
                            RuneCategory.Cr => HandleStartCr(ref this),
                            RuneCategory.Lf => State.BreakConsumeLast,
                            RuneCategory.Newline => State.BreakConsumeLast,
                            _ => HandleStart(ref this)
                        },
                        State.AHLetter or State.HLetter => rune.Category switch
                        {
                            RuneCategory.ALetter => State.AHLetter,
                            RuneCategory.HLetter => State.HLetter,
                            RuneCategory.Numeric => State.Numeric,
                            RuneCategory.ExtendNumLet => State.ExtendNumLet,
                            RuneCategory.SingleQuote when state == State.HLetter => State.FormatExtendAcceptQLetter,
                            RuneCategory.SingleQuote or
                            RuneCategory.MidLetter or
                            RuneCategory.MidNum => FormatExtend(ref this, State.FormatExtendRequireAHLetter, ref savedRune, ref savedIndex),
                            _ => State.BreakConsumeNone | state
                        },
                        State.Numeric => rune.Category switch
                        {
                            RuneCategory.ALetter => State.AHLetter,
                            RuneCategory.HLetter => State.HLetter,
                            RuneCategory.Numeric => State.Numeric,
                            RuneCategory.ExtendNumLet => State.ExtendNumLet,
                            RuneCategory.SingleQuote or
                            RuneCategory.MidLetter or
                            RuneCategory.MidNum => FormatExtend(ref this, State.FormatExtendRequireNumeric, ref savedRune, ref savedIndex),
                            _ => State.BreakConsumeNone | state
                        },
                        State.Katakana => rune.Category switch
                        {
                            RuneCategory.Katakana => State.Katakana,
                            RuneCategory.ExtendNumLet => State.ExtendNumLet,
                            _ => State.BreakConsumeNone
                        },
                        State.ExtendNumLet => rune.Category switch
                        {
                            RuneCategory.ALetter => State.AHLetter,
                            RuneCategory.HLetter => State.HLetter,
                            RuneCategory.Numeric => State.Numeric,
                            RuneCategory.Katakana => State.Katakana,
                            RuneCategory.ExtendNumLet => State.ExtendNumLet,
                            _ => State.BreakConsumeNone  
                        },
                        State.RegionalIndicatorFull => State.BreakConsumeNone,
                        State.RegionalIndicatorHalf => rune.Category == RuneCategory.RegionalIndicator
                            ? State.RegionalIndicatorFull
                            : State.BreakConsumeNone,
                        State.FormatExtendRequireNumeric when rune.Category == RuneCategory.Numeric => State.Numeric,
                        State.FormatExtendRequireAHLetter or State.FormatExtendAcceptQLetter when rune.Category == RuneCategory.ALetter => State.AHLetter,
                        State.FormatExtendRequireAHLetter or State.FormatExtendAcceptQLetter when rune.Category == RuneCategory.HLetter => State.HLetter,
                        State.FormatExtendRequireHLetter when rune.Category == RuneCategory.HLetter => State.HLetter,
                        State.FormatExtendAcceptNone or State.FormatExtendAcceptQLetter => State.BreakConsumeNone,
                        State.WSegSpace => rune.Category == RuneCategory.WSegSpace && handleFormatExtend
                            ? State.WSegSpace
                            : State.BreakConsumeNone,
                        State.Emoji => State.BreakConsumeNone,
                        State.Zwj => State.BreakConsumeNone,
                        _ => State.BreakConsumeLast
                    };

                    if ((state & BreakMask) != default)
                        break;

                    static State HandleStart(ref WordEnumerator self)
                    {
                        var source = self._source;
                        if (TryDecodeRune(source, out var rune))
                        {
                            if (rune.Category == RuneCategory.Extend ||
                                rune.Category == RuneCategory.Format ||
                                rune.Category == RuneCategory.Zwj)
                            {
                                self._currentRune = rune;
                                return State.FormatExtendAcceptNone;
                            }
                        }

                        return State.BreakConsumeLast;
                    }

                    static State HandleStartCr(ref WordEnumerator self)
                    {
                        var source = self._source;
                        if (TryDecodeRune(source, out var rune) &&
                            rune.Category == RuneCategory.Lf)
                        {
                            self._currentRune = default;
                            self._currentIndex += rune.Value.Utf8SequenceLength;
                        }

                        return State.BreakConsumeNone;
                    }

                    static State FormatExtend(ref WordEnumerator self, State state, ref RuneInfo savedRune, ref int savedIndex)
                    {
                        Debug.Assert(
                            state == State.FormatExtendRequireAHLetter ||
                            state == State.FormatExtendRequireHLetter ||
                            state == State.FormatExtendRequireNumeric);

                        savedRune = self._currentRune;
                        savedIndex = self._currentIndex;

                        return state;
                    }

                    static bool TryDecodeRune(ReadOnlySpan<char> source, out RuneInfo runeInfo)
                    {
                        if (Rune.DecodeFromUtf16(source, out var rune, out _) == OperationStatus.Done)
                        {
                            runeInfo = new RuneInfo(rune, GetRuneCategory(rune));
                            return true;
                        }
                        else
                        {
                            runeInfo = new RuneInfo(rune, RuneCategory.Any);
                            return false;
                        }
                    }
                }

                switch (state & StateMask)
                {
                    case State.AHLetter:
                    case State.HLetter:
                    case State.Numeric:
                        _currentRune = savedRune;
                        _currentIndex = savedIndex;
                        break;
                }

                if (state.HasFlag(State.BreakConsumeLast))
                {
                    _currentIndex += _currentRune.Value.Utf16SequenceLength;
                    _currentRune = default;
                }

                _current = _source[startIndex.._currentIndex];
                return true;
            }
        }

        private readonly struct RuneInfo
        {
            public readonly Rune Value;
            public readonly RuneCategory Category;

            public RuneInfo(Rune value, RuneCategory category) =>
                (Value, Category) = (value, category);
        }

        [Flags]
        private enum State
        {
            Start,
            BreakConsumeLast = 1 << 30,
            BreakConsumeNone = 1 << 31,
            AHLetter,
            HLetter,
            Numeric,
            Katakana,
            ExtendNumLet,
            RegionalIndicatorFull,
            RegionalIndicatorHalf,
            RegionalIndicatorUnknown,
            FormatExtendAcceptAny,
            FormatExtendAcceptNone,
            FormatExtendAcceptQLetter,
            FormatExtendRequireAHLetter,
            FormatExtendRequireHLetter,
            FormatExtendRequireNumeric,
            Zwj,
            Emoji,
            WSegSpace,
        }

        private enum RuneCategory
        {
            None,
            ALetter,
            Any,
            Cr,
            DoubleQuote,
            Extend,
            ExtendNumLet,
            Format,
            HLetter,
            Katakana,
            Lf,
            MidLetter,
            MidNum,
            MidNumLet,
            Newline,
            Numeric,
            RegionalIndicator,
            SingleQuote,
            WSegSpace,
            Zwj,
        }

        private static RuneCategory GetRuneCategory(Rune rune)
        {
            int lo = 0;
            int hi = RuneCategories.Length - 1;
            
            while (lo <= hi)
            {
                int i = lo + ((hi - lo) >> 1);
                var range = RuneCategories[i];

                if (rune < range.Start)
                {
                    hi = i - 1;
                    continue;
                }

                if (rune > range.End)
                {
                    lo = i + 1;
                    continue;
                }
                
                return range.Value;

            }

            return RuneCategory.Any;
        }

        private static readonly (Rune Start, Rune End, RuneCategory Value)[] RuneCategories = new []
        {
            (new Rune(0x000a), new Rune(0x000a), RuneCategory.Lf),
            (new Rune(0x000b), new Rune(0x000c), RuneCategory.Newline),
            (new Rune(0x000d), new Rune(0x000d), RuneCategory.Cr),
            (new Rune(0x0020), new Rune(0x0020), RuneCategory.WSegSpace),
            (new Rune(0x0022), new Rune(0x0022), RuneCategory.DoubleQuote),
            (new Rune(0x0027), new Rune(0x0027), RuneCategory.SingleQuote),
            (new Rune(0x002c), new Rune(0x002c), RuneCategory.MidNum),
            (new Rune(0x002e), new Rune(0x002e), RuneCategory.MidNumLet),
            (new Rune(0x0030), new Rune(0x0039), RuneCategory.Numeric),
            (new Rune(0x003a), new Rune(0x003a), RuneCategory.MidLetter),
            (new Rune(0x003b), new Rune(0x003b), RuneCategory.MidNum),
            (new Rune(0x0041), new Rune(0x005a), RuneCategory.ALetter),
            (new Rune(0x005f), new Rune(0x005f), RuneCategory.ExtendNumLet),
            (new Rune(0x0061), new Rune(0x007a), RuneCategory.ALetter),
            (new Rune(0x0085), new Rune(0x0085), RuneCategory.Newline),
            (new Rune(0x00aa), new Rune(0x00aa), RuneCategory.ALetter),
            (new Rune(0x00ad), new Rune(0x00ad), RuneCategory.Format),
            (new Rune(0x00b5), new Rune(0x00b5), RuneCategory.ALetter),
            (new Rune(0x00b7), new Rune(0x00b7), RuneCategory.MidLetter),
            (new Rune(0x00ba), new Rune(0x00ba), RuneCategory.ALetter),
            (new Rune(0x00c0), new Rune(0x00d6), RuneCategory.ALetter),
            (new Rune(0x00d8), new Rune(0x00f6), RuneCategory.ALetter),
            (new Rune(0x00f8), new Rune(0x02d7), RuneCategory.ALetter),
            (new Rune(0x02de), new Rune(0x02ff), RuneCategory.ALetter),
            (new Rune(0x0300), new Rune(0x036f), RuneCategory.Extend),
            (new Rune(0x0370), new Rune(0x0374), RuneCategory.ALetter),
            (new Rune(0x0376), new Rune(0x0377), RuneCategory.ALetter),
            (new Rune(0x037a), new Rune(0x037d), RuneCategory.ALetter),
            (new Rune(0x037e), new Rune(0x037e), RuneCategory.MidNum),
            (new Rune(0x037f), new Rune(0x037f), RuneCategory.ALetter),
            (new Rune(0x0386), new Rune(0x0386), RuneCategory.ALetter),
            (new Rune(0x0387), new Rune(0x0387), RuneCategory.MidLetter),
            (new Rune(0x0388), new Rune(0x038a), RuneCategory.ALetter),
            (new Rune(0x038c), new Rune(0x038c), RuneCategory.ALetter),
            (new Rune(0x038e), new Rune(0x03a1), RuneCategory.ALetter),
            (new Rune(0x03a3), new Rune(0x03f5), RuneCategory.ALetter),
            (new Rune(0x03f7), new Rune(0x0481), RuneCategory.ALetter),
            (new Rune(0x0483), new Rune(0x0489), RuneCategory.Extend),
            (new Rune(0x048a), new Rune(0x052f), RuneCategory.ALetter),
            (new Rune(0x0531), new Rune(0x0556), RuneCategory.ALetter),
            (new Rune(0x0559), new Rune(0x055c), RuneCategory.ALetter),
            (new Rune(0x055e), new Rune(0x055e), RuneCategory.ALetter),
            (new Rune(0x055f), new Rune(0x055f), RuneCategory.MidLetter),
            (new Rune(0x0560), new Rune(0x0588), RuneCategory.ALetter),
            (new Rune(0x0589), new Rune(0x0589), RuneCategory.MidNum),
            (new Rune(0x058a), new Rune(0x058a), RuneCategory.ALetter),
            (new Rune(0x0591), new Rune(0x05bd), RuneCategory.Extend),
            (new Rune(0x05bf), new Rune(0x05bf), RuneCategory.Extend),
            (new Rune(0x05c1), new Rune(0x05c2), RuneCategory.Extend),
            (new Rune(0x05c4), new Rune(0x05c5), RuneCategory.Extend),
            (new Rune(0x05c7), new Rune(0x05c7), RuneCategory.Extend),
            (new Rune(0x05d0), new Rune(0x05ea), RuneCategory.HLetter),
            (new Rune(0x05ef), new Rune(0x05f2), RuneCategory.HLetter),
            (new Rune(0x05f3), new Rune(0x05f3), RuneCategory.ALetter),
            (new Rune(0x05f4), new Rune(0x05f4), RuneCategory.MidLetter),
            (new Rune(0x0600), new Rune(0x0605), RuneCategory.Format),
            (new Rune(0x060c), new Rune(0x060d), RuneCategory.MidNum),
            (new Rune(0x0610), new Rune(0x061a), RuneCategory.Extend),
            (new Rune(0x061c), new Rune(0x061c), RuneCategory.Format),
            (new Rune(0x0620), new Rune(0x064a), RuneCategory.ALetter),
            (new Rune(0x064b), new Rune(0x065f), RuneCategory.Extend),
            (new Rune(0x0660), new Rune(0x0669), RuneCategory.Numeric),
            (new Rune(0x066b), new Rune(0x066b), RuneCategory.Numeric),
            (new Rune(0x066c), new Rune(0x066c), RuneCategory.MidNum),
            (new Rune(0x066e), new Rune(0x066f), RuneCategory.ALetter),
            (new Rune(0x0670), new Rune(0x0670), RuneCategory.Extend),
            (new Rune(0x0671), new Rune(0x06d3), RuneCategory.ALetter),
            (new Rune(0x06d5), new Rune(0x06d5), RuneCategory.ALetter),
            (new Rune(0x06d6), new Rune(0x06dc), RuneCategory.Extend),
            (new Rune(0x06dd), new Rune(0x06dd), RuneCategory.Format),
            (new Rune(0x06df), new Rune(0x06e4), RuneCategory.Extend),
            (new Rune(0x06e5), new Rune(0x06e6), RuneCategory.ALetter),
            (new Rune(0x06e7), new Rune(0x06e8), RuneCategory.Extend),
            (new Rune(0x06ea), new Rune(0x06ed), RuneCategory.Extend),
            (new Rune(0x06ee), new Rune(0x06ef), RuneCategory.ALetter),
            (new Rune(0x06f0), new Rune(0x06f9), RuneCategory.Numeric),
            (new Rune(0x06fa), new Rune(0x06fc), RuneCategory.ALetter),
            (new Rune(0x06ff), new Rune(0x06ff), RuneCategory.ALetter),
            (new Rune(0x070f), new Rune(0x070f), RuneCategory.Format),
            (new Rune(0x0710), new Rune(0x0710), RuneCategory.ALetter),
            (new Rune(0x0711), new Rune(0x0711), RuneCategory.Extend),
            (new Rune(0x0712), new Rune(0x072f), RuneCategory.ALetter),
            (new Rune(0x0730), new Rune(0x074a), RuneCategory.Extend),
            (new Rune(0x074d), new Rune(0x07a5), RuneCategory.ALetter),
            (new Rune(0x07a6), new Rune(0x07b0), RuneCategory.Extend),
            (new Rune(0x07b1), new Rune(0x07b1), RuneCategory.ALetter),
            (new Rune(0x07c0), new Rune(0x07c9), RuneCategory.Numeric),
            (new Rune(0x07ca), new Rune(0x07ea), RuneCategory.ALetter),
            (new Rune(0x07eb), new Rune(0x07f3), RuneCategory.Extend),
            (new Rune(0x07f4), new Rune(0x07f5), RuneCategory.ALetter),
            (new Rune(0x07f8), new Rune(0x07f8), RuneCategory.MidNum),
            (new Rune(0x07fa), new Rune(0x07fa), RuneCategory.ALetter),
            (new Rune(0x07fd), new Rune(0x07fd), RuneCategory.Extend),
            (new Rune(0x0800), new Rune(0x0815), RuneCategory.ALetter),
            (new Rune(0x0816), new Rune(0x0819), RuneCategory.Extend),
            (new Rune(0x081a), new Rune(0x081a), RuneCategory.ALetter),
            (new Rune(0x081b), new Rune(0x0823), RuneCategory.Extend),
            (new Rune(0x0824), new Rune(0x0824), RuneCategory.ALetter),
            (new Rune(0x0825), new Rune(0x0827), RuneCategory.Extend),
            (new Rune(0x0828), new Rune(0x0828), RuneCategory.ALetter),
            (new Rune(0x0829), new Rune(0x082d), RuneCategory.Extend),
            (new Rune(0x0840), new Rune(0x0858), RuneCategory.ALetter),
            (new Rune(0x0859), new Rune(0x085b), RuneCategory.Extend),
            (new Rune(0x0860), new Rune(0x086a), RuneCategory.ALetter),
            (new Rune(0x08a0), new Rune(0x08b4), RuneCategory.ALetter),
            (new Rune(0x08b6), new Rune(0x08c7), RuneCategory.ALetter),
            (new Rune(0x08d3), new Rune(0x08e1), RuneCategory.Extend),
            (new Rune(0x08e2), new Rune(0x08e2), RuneCategory.Format),
            (new Rune(0x08e3), new Rune(0x0903), RuneCategory.Extend),
            (new Rune(0x0904), new Rune(0x0939), RuneCategory.ALetter),
            (new Rune(0x093a), new Rune(0x093c), RuneCategory.Extend),
            (new Rune(0x093d), new Rune(0x093d), RuneCategory.ALetter),
            (new Rune(0x093e), new Rune(0x094f), RuneCategory.Extend),
            (new Rune(0x0950), new Rune(0x0950), RuneCategory.ALetter),
            (new Rune(0x0951), new Rune(0x0957), RuneCategory.Extend),
            (new Rune(0x0958), new Rune(0x0961), RuneCategory.ALetter),
            (new Rune(0x0962), new Rune(0x0963), RuneCategory.Extend),
            (new Rune(0x0966), new Rune(0x096f), RuneCategory.Numeric),
            (new Rune(0x0971), new Rune(0x0980), RuneCategory.ALetter),
            (new Rune(0x0981), new Rune(0x0983), RuneCategory.Extend),
            (new Rune(0x0985), new Rune(0x098c), RuneCategory.ALetter),
            (new Rune(0x098f), new Rune(0x0990), RuneCategory.ALetter),
            (new Rune(0x0993), new Rune(0x09a8), RuneCategory.ALetter),
            (new Rune(0x09aa), new Rune(0x09b0), RuneCategory.ALetter),
            (new Rune(0x09b2), new Rune(0x09b2), RuneCategory.ALetter),
            (new Rune(0x09b6), new Rune(0x09b9), RuneCategory.ALetter),
            (new Rune(0x09bc), new Rune(0x09bc), RuneCategory.Extend),
            (new Rune(0x09bd), new Rune(0x09bd), RuneCategory.ALetter),
            (new Rune(0x09be), new Rune(0x09c4), RuneCategory.Extend),
            (new Rune(0x09c7), new Rune(0x09c8), RuneCategory.Extend),
            (new Rune(0x09cb), new Rune(0x09cd), RuneCategory.Extend),
            (new Rune(0x09ce), new Rune(0x09ce), RuneCategory.ALetter),
            (new Rune(0x09d7), new Rune(0x09d7), RuneCategory.Extend),
            (new Rune(0x09dc), new Rune(0x09dd), RuneCategory.ALetter),
            (new Rune(0x09df), new Rune(0x09e1), RuneCategory.ALetter),
            (new Rune(0x09e2), new Rune(0x09e3), RuneCategory.Extend),
            (new Rune(0x09e6), new Rune(0x09ef), RuneCategory.Numeric),
            (new Rune(0x09f0), new Rune(0x09f1), RuneCategory.ALetter),
            (new Rune(0x09fc), new Rune(0x09fc), RuneCategory.ALetter),
            (new Rune(0x09fe), new Rune(0x09fe), RuneCategory.Extend),
            (new Rune(0x0a01), new Rune(0x0a03), RuneCategory.Extend),
            (new Rune(0x0a05), new Rune(0x0a0a), RuneCategory.ALetter),
            (new Rune(0x0a0f), new Rune(0x0a10), RuneCategory.ALetter),
            (new Rune(0x0a13), new Rune(0x0a28), RuneCategory.ALetter),
            (new Rune(0x0a2a), new Rune(0x0a30), RuneCategory.ALetter),
            (new Rune(0x0a32), new Rune(0x0a33), RuneCategory.ALetter),
            (new Rune(0x0a35), new Rune(0x0a36), RuneCategory.ALetter),
            (new Rune(0x0a38), new Rune(0x0a39), RuneCategory.ALetter),
            (new Rune(0x0a3c), new Rune(0x0a3c), RuneCategory.Extend),
            (new Rune(0x0a3e), new Rune(0x0a42), RuneCategory.Extend),
            (new Rune(0x0a47), new Rune(0x0a48), RuneCategory.Extend),
            (new Rune(0x0a4b), new Rune(0x0a4d), RuneCategory.Extend),
            (new Rune(0x0a51), new Rune(0x0a51), RuneCategory.Extend),
            (new Rune(0x0a59), new Rune(0x0a5c), RuneCategory.ALetter),
            (new Rune(0x0a5e), new Rune(0x0a5e), RuneCategory.ALetter),
            (new Rune(0x0a66), new Rune(0x0a6f), RuneCategory.Numeric),
            (new Rune(0x0a70), new Rune(0x0a71), RuneCategory.Extend),
            (new Rune(0x0a72), new Rune(0x0a74), RuneCategory.ALetter),
            (new Rune(0x0a75), new Rune(0x0a75), RuneCategory.Extend),
            (new Rune(0x0a81), new Rune(0x0a83), RuneCategory.Extend),
            (new Rune(0x0a85), new Rune(0x0a8d), RuneCategory.ALetter),
            (new Rune(0x0a8f), new Rune(0x0a91), RuneCategory.ALetter),
            (new Rune(0x0a93), new Rune(0x0aa8), RuneCategory.ALetter),
            (new Rune(0x0aaa), new Rune(0x0ab0), RuneCategory.ALetter),
            (new Rune(0x0ab2), new Rune(0x0ab3), RuneCategory.ALetter),
            (new Rune(0x0ab5), new Rune(0x0ab9), RuneCategory.ALetter),
            (new Rune(0x0abc), new Rune(0x0abc), RuneCategory.Extend),
            (new Rune(0x0abd), new Rune(0x0abd), RuneCategory.ALetter),
            (new Rune(0x0abe), new Rune(0x0ac5), RuneCategory.Extend),
            (new Rune(0x0ac7), new Rune(0x0ac9), RuneCategory.Extend),
            (new Rune(0x0acb), new Rune(0x0acd), RuneCategory.Extend),
            (new Rune(0x0ad0), new Rune(0x0ad0), RuneCategory.ALetter),
            (new Rune(0x0ae0), new Rune(0x0ae1), RuneCategory.ALetter),
            (new Rune(0x0ae2), new Rune(0x0ae3), RuneCategory.Extend),
            (new Rune(0x0ae6), new Rune(0x0aef), RuneCategory.Numeric),
            (new Rune(0x0af9), new Rune(0x0af9), RuneCategory.ALetter),
            (new Rune(0x0afa), new Rune(0x0aff), RuneCategory.Extend),
            (new Rune(0x0b01), new Rune(0x0b03), RuneCategory.Extend),
            (new Rune(0x0b05), new Rune(0x0b0c), RuneCategory.ALetter),
            (new Rune(0x0b0f), new Rune(0x0b10), RuneCategory.ALetter),
            (new Rune(0x0b13), new Rune(0x0b28), RuneCategory.ALetter),
            (new Rune(0x0b2a), new Rune(0x0b30), RuneCategory.ALetter),
            (new Rune(0x0b32), new Rune(0x0b33), RuneCategory.ALetter),
            (new Rune(0x0b35), new Rune(0x0b39), RuneCategory.ALetter),
            (new Rune(0x0b3c), new Rune(0x0b3c), RuneCategory.Extend),
            (new Rune(0x0b3d), new Rune(0x0b3d), RuneCategory.ALetter),
            (new Rune(0x0b3e), new Rune(0x0b44), RuneCategory.Extend),
            (new Rune(0x0b47), new Rune(0x0b48), RuneCategory.Extend),
            (new Rune(0x0b4b), new Rune(0x0b4d), RuneCategory.Extend),
            (new Rune(0x0b55), new Rune(0x0b57), RuneCategory.Extend),
            (new Rune(0x0b5c), new Rune(0x0b5d), RuneCategory.ALetter),
            (new Rune(0x0b5f), new Rune(0x0b61), RuneCategory.ALetter),
            (new Rune(0x0b62), new Rune(0x0b63), RuneCategory.Extend),
            (new Rune(0x0b66), new Rune(0x0b6f), RuneCategory.Numeric),
            (new Rune(0x0b71), new Rune(0x0b71), RuneCategory.ALetter),
            (new Rune(0x0b82), new Rune(0x0b82), RuneCategory.Extend),
            (new Rune(0x0b83), new Rune(0x0b83), RuneCategory.ALetter),
            (new Rune(0x0b85), new Rune(0x0b8a), RuneCategory.ALetter),
            (new Rune(0x0b8e), new Rune(0x0b90), RuneCategory.ALetter),
            (new Rune(0x0b92), new Rune(0x0b95), RuneCategory.ALetter),
            (new Rune(0x0b99), new Rune(0x0b9a), RuneCategory.ALetter),
            (new Rune(0x0b9c), new Rune(0x0b9c), RuneCategory.ALetter),
            (new Rune(0x0b9e), new Rune(0x0b9f), RuneCategory.ALetter),
            (new Rune(0x0ba3), new Rune(0x0ba4), RuneCategory.ALetter),
            (new Rune(0x0ba8), new Rune(0x0baa), RuneCategory.ALetter),
            (new Rune(0x0bae), new Rune(0x0bb9), RuneCategory.ALetter),
            (new Rune(0x0bbe), new Rune(0x0bc2), RuneCategory.Extend),
            (new Rune(0x0bc6), new Rune(0x0bc8), RuneCategory.Extend),
            (new Rune(0x0bca), new Rune(0x0bcd), RuneCategory.Extend),
            (new Rune(0x0bd0), new Rune(0x0bd0), RuneCategory.ALetter),
            (new Rune(0x0bd7), new Rune(0x0bd7), RuneCategory.Extend),
            (new Rune(0x0be6), new Rune(0x0bef), RuneCategory.Numeric),
            (new Rune(0x0c00), new Rune(0x0c04), RuneCategory.Extend),
            (new Rune(0x0c05), new Rune(0x0c0c), RuneCategory.ALetter),
            (new Rune(0x0c0e), new Rune(0x0c10), RuneCategory.ALetter),
            (new Rune(0x0c12), new Rune(0x0c28), RuneCategory.ALetter),
            (new Rune(0x0c2a), new Rune(0x0c39), RuneCategory.ALetter),
            (new Rune(0x0c3d), new Rune(0x0c3d), RuneCategory.ALetter),
            (new Rune(0x0c3e), new Rune(0x0c44), RuneCategory.Extend),
            (new Rune(0x0c46), new Rune(0x0c48), RuneCategory.Extend),
            (new Rune(0x0c4a), new Rune(0x0c4d), RuneCategory.Extend),
            (new Rune(0x0c55), new Rune(0x0c56), RuneCategory.Extend),
            (new Rune(0x0c58), new Rune(0x0c5a), RuneCategory.ALetter),
            (new Rune(0x0c60), new Rune(0x0c61), RuneCategory.ALetter),
            (new Rune(0x0c62), new Rune(0x0c63), RuneCategory.Extend),
            (new Rune(0x0c66), new Rune(0x0c6f), RuneCategory.Numeric),
            (new Rune(0x0c80), new Rune(0x0c80), RuneCategory.ALetter),
            (new Rune(0x0c81), new Rune(0x0c83), RuneCategory.Extend),
            (new Rune(0x0c85), new Rune(0x0c8c), RuneCategory.ALetter),
            (new Rune(0x0c8e), new Rune(0x0c90), RuneCategory.ALetter),
            (new Rune(0x0c92), new Rune(0x0ca8), RuneCategory.ALetter),
            (new Rune(0x0caa), new Rune(0x0cb3), RuneCategory.ALetter),
            (new Rune(0x0cb5), new Rune(0x0cb9), RuneCategory.ALetter),
            (new Rune(0x0cbc), new Rune(0x0cbc), RuneCategory.Extend),
            (new Rune(0x0cbd), new Rune(0x0cbd), RuneCategory.ALetter),
            (new Rune(0x0cbe), new Rune(0x0cc4), RuneCategory.Extend),
            (new Rune(0x0cc6), new Rune(0x0cc8), RuneCategory.Extend),
            (new Rune(0x0cca), new Rune(0x0ccd), RuneCategory.Extend),
            (new Rune(0x0cd5), new Rune(0x0cd6), RuneCategory.Extend),
            (new Rune(0x0cde), new Rune(0x0cde), RuneCategory.ALetter),
            (new Rune(0x0ce0), new Rune(0x0ce1), RuneCategory.ALetter),
            (new Rune(0x0ce2), new Rune(0x0ce3), RuneCategory.Extend),
            (new Rune(0x0ce6), new Rune(0x0cef), RuneCategory.Numeric),
            (new Rune(0x0cf1), new Rune(0x0cf2), RuneCategory.ALetter),
            (new Rune(0x0d00), new Rune(0x0d03), RuneCategory.Extend),
            (new Rune(0x0d04), new Rune(0x0d0c), RuneCategory.ALetter),
            (new Rune(0x0d0e), new Rune(0x0d10), RuneCategory.ALetter),
            (new Rune(0x0d12), new Rune(0x0d3a), RuneCategory.ALetter),
            (new Rune(0x0d3b), new Rune(0x0d3c), RuneCategory.Extend),
            (new Rune(0x0d3d), new Rune(0x0d3d), RuneCategory.ALetter),
            (new Rune(0x0d3e), new Rune(0x0d44), RuneCategory.Extend),
            (new Rune(0x0d46), new Rune(0x0d48), RuneCategory.Extend),
            (new Rune(0x0d4a), new Rune(0x0d4d), RuneCategory.Extend),
            (new Rune(0x0d4e), new Rune(0x0d4e), RuneCategory.ALetter),
            (new Rune(0x0d54), new Rune(0x0d56), RuneCategory.ALetter),
            (new Rune(0x0d57), new Rune(0x0d57), RuneCategory.Extend),
            (new Rune(0x0d5f), new Rune(0x0d61), RuneCategory.ALetter),
            (new Rune(0x0d62), new Rune(0x0d63), RuneCategory.Extend),
            (new Rune(0x0d66), new Rune(0x0d6f), RuneCategory.Numeric),
            (new Rune(0x0d7a), new Rune(0x0d7f), RuneCategory.ALetter),
            (new Rune(0x0d81), new Rune(0x0d83), RuneCategory.Extend),
            (new Rune(0x0d85), new Rune(0x0d96), RuneCategory.ALetter),
            (new Rune(0x0d9a), new Rune(0x0db1), RuneCategory.ALetter),
            (new Rune(0x0db3), new Rune(0x0dbb), RuneCategory.ALetter),
            (new Rune(0x0dbd), new Rune(0x0dbd), RuneCategory.ALetter),
            (new Rune(0x0dc0), new Rune(0x0dc6), RuneCategory.ALetter),
            (new Rune(0x0dca), new Rune(0x0dca), RuneCategory.Extend),
            (new Rune(0x0dcf), new Rune(0x0dd4), RuneCategory.Extend),
            (new Rune(0x0dd6), new Rune(0x0dd6), RuneCategory.Extend),
            (new Rune(0x0dd8), new Rune(0x0ddf), RuneCategory.Extend),
            (new Rune(0x0de6), new Rune(0x0def), RuneCategory.Numeric),
            (new Rune(0x0df2), new Rune(0x0df3), RuneCategory.Extend),
            (new Rune(0x0e31), new Rune(0x0e31), RuneCategory.Extend),
            (new Rune(0x0e34), new Rune(0x0e3a), RuneCategory.Extend),
            (new Rune(0x0e47), new Rune(0x0e4e), RuneCategory.Extend),
            (new Rune(0x0e50), new Rune(0x0e59), RuneCategory.Numeric),
            (new Rune(0x0eb1), new Rune(0x0eb1), RuneCategory.Extend),
            (new Rune(0x0eb4), new Rune(0x0ebc), RuneCategory.Extend),
            (new Rune(0x0ec8), new Rune(0x0ecd), RuneCategory.Extend),
            (new Rune(0x0ed0), new Rune(0x0ed9), RuneCategory.Numeric),
            (new Rune(0x0f00), new Rune(0x0f00), RuneCategory.ALetter),
            (new Rune(0x0f18), new Rune(0x0f19), RuneCategory.Extend),
            (new Rune(0x0f20), new Rune(0x0f29), RuneCategory.Numeric),
            (new Rune(0x0f35), new Rune(0x0f35), RuneCategory.Extend),
            (new Rune(0x0f37), new Rune(0x0f37), RuneCategory.Extend),
            (new Rune(0x0f39), new Rune(0x0f39), RuneCategory.Extend),
            (new Rune(0x0f3e), new Rune(0x0f3f), RuneCategory.Extend),
            (new Rune(0x0f40), new Rune(0x0f47), RuneCategory.ALetter),
            (new Rune(0x0f49), new Rune(0x0f6c), RuneCategory.ALetter),
            (new Rune(0x0f71), new Rune(0x0f84), RuneCategory.Extend),
            (new Rune(0x0f86), new Rune(0x0f87), RuneCategory.Extend),
            (new Rune(0x0f88), new Rune(0x0f8c), RuneCategory.ALetter),
            (new Rune(0x0f8d), new Rune(0x0f97), RuneCategory.Extend),
            (new Rune(0x0f99), new Rune(0x0fbc), RuneCategory.Extend),
            (new Rune(0x0fc6), new Rune(0x0fc6), RuneCategory.Extend),
            (new Rune(0x102b), new Rune(0x103e), RuneCategory.Extend),
            (new Rune(0x1040), new Rune(0x1049), RuneCategory.Numeric),
            (new Rune(0x1056), new Rune(0x1059), RuneCategory.Extend),
            (new Rune(0x105e), new Rune(0x1060), RuneCategory.Extend),
            (new Rune(0x1062), new Rune(0x1064), RuneCategory.Extend),
            (new Rune(0x1067), new Rune(0x106d), RuneCategory.Extend),
            (new Rune(0x1071), new Rune(0x1074), RuneCategory.Extend),
            (new Rune(0x1082), new Rune(0x108d), RuneCategory.Extend),
            (new Rune(0x108f), new Rune(0x108f), RuneCategory.Extend),
            (new Rune(0x1090), new Rune(0x1099), RuneCategory.Numeric),
            (new Rune(0x109a), new Rune(0x109d), RuneCategory.Extend),
            (new Rune(0x10a0), new Rune(0x10c5), RuneCategory.ALetter),
            (new Rune(0x10c7), new Rune(0x10c7), RuneCategory.ALetter),
            (new Rune(0x10cd), new Rune(0x10cd), RuneCategory.ALetter),
            (new Rune(0x10d0), new Rune(0x10fa), RuneCategory.ALetter),
            (new Rune(0x10fc), new Rune(0x1248), RuneCategory.ALetter),
            (new Rune(0x124a), new Rune(0x124d), RuneCategory.ALetter),
            (new Rune(0x1250), new Rune(0x1256), RuneCategory.ALetter),
            (new Rune(0x1258), new Rune(0x1258), RuneCategory.ALetter),
            (new Rune(0x125a), new Rune(0x125d), RuneCategory.ALetter),
            (new Rune(0x1260), new Rune(0x1288), RuneCategory.ALetter),
            (new Rune(0x128a), new Rune(0x128d), RuneCategory.ALetter),
            (new Rune(0x1290), new Rune(0x12b0), RuneCategory.ALetter),
            (new Rune(0x12b2), new Rune(0x12b5), RuneCategory.ALetter),
            (new Rune(0x12b8), new Rune(0x12be), RuneCategory.ALetter),
            (new Rune(0x12c0), new Rune(0x12c0), RuneCategory.ALetter),
            (new Rune(0x12c2), new Rune(0x12c5), RuneCategory.ALetter),
            (new Rune(0x12c8), new Rune(0x12d6), RuneCategory.ALetter),
            (new Rune(0x12d8), new Rune(0x1310), RuneCategory.ALetter),
            (new Rune(0x1312), new Rune(0x1315), RuneCategory.ALetter),
            (new Rune(0x1318), new Rune(0x135a), RuneCategory.ALetter),
            (new Rune(0x135d), new Rune(0x135f), RuneCategory.Extend),
            (new Rune(0x1380), new Rune(0x138f), RuneCategory.ALetter),
            (new Rune(0x13a0), new Rune(0x13f5), RuneCategory.ALetter),
            (new Rune(0x13f8), new Rune(0x13fd), RuneCategory.ALetter),
            (new Rune(0x1401), new Rune(0x166c), RuneCategory.ALetter),
            (new Rune(0x166f), new Rune(0x167f), RuneCategory.ALetter),
            (new Rune(0x1680), new Rune(0x1680), RuneCategory.WSegSpace),
            (new Rune(0x1681), new Rune(0x169a), RuneCategory.ALetter),
            (new Rune(0x16a0), new Rune(0x16ea), RuneCategory.ALetter),
            (new Rune(0x16ee), new Rune(0x16f8), RuneCategory.ALetter),
            (new Rune(0x1700), new Rune(0x170c), RuneCategory.ALetter),
            (new Rune(0x170e), new Rune(0x1711), RuneCategory.ALetter),
            (new Rune(0x1712), new Rune(0x1714), RuneCategory.Extend),
            (new Rune(0x1720), new Rune(0x1731), RuneCategory.ALetter),
            (new Rune(0x1732), new Rune(0x1734), RuneCategory.Extend),
            (new Rune(0x1740), new Rune(0x1751), RuneCategory.ALetter),
            (new Rune(0x1752), new Rune(0x1753), RuneCategory.Extend),
            (new Rune(0x1760), new Rune(0x176c), RuneCategory.ALetter),
            (new Rune(0x176e), new Rune(0x1770), RuneCategory.ALetter),
            (new Rune(0x1772), new Rune(0x1773), RuneCategory.Extend),
            (new Rune(0x17b4), new Rune(0x17d3), RuneCategory.Extend),
            (new Rune(0x17dd), new Rune(0x17dd), RuneCategory.Extend),
            (new Rune(0x17e0), new Rune(0x17e9), RuneCategory.Numeric),
            (new Rune(0x180b), new Rune(0x180d), RuneCategory.Extend),
            (new Rune(0x180e), new Rune(0x180e), RuneCategory.Format),
            (new Rune(0x1810), new Rune(0x1819), RuneCategory.Numeric),
            (new Rune(0x1820), new Rune(0x1878), RuneCategory.ALetter),
            (new Rune(0x1880), new Rune(0x1884), RuneCategory.ALetter),
            (new Rune(0x1885), new Rune(0x1886), RuneCategory.Extend),
            (new Rune(0x1887), new Rune(0x18a8), RuneCategory.ALetter),
            (new Rune(0x18a9), new Rune(0x18a9), RuneCategory.Extend),
            (new Rune(0x18aa), new Rune(0x18aa), RuneCategory.ALetter),
            (new Rune(0x18b0), new Rune(0x18f5), RuneCategory.ALetter),
            (new Rune(0x1900), new Rune(0x191e), RuneCategory.ALetter),
            (new Rune(0x1920), new Rune(0x192b), RuneCategory.Extend),
            (new Rune(0x1930), new Rune(0x193b), RuneCategory.Extend),
            (new Rune(0x1946), new Rune(0x194f), RuneCategory.Numeric),
            (new Rune(0x19d0), new Rune(0x19d9), RuneCategory.Numeric),
            (new Rune(0x1a00), new Rune(0x1a16), RuneCategory.ALetter),
            (new Rune(0x1a17), new Rune(0x1a1b), RuneCategory.Extend),
            (new Rune(0x1a55), new Rune(0x1a5e), RuneCategory.Extend),
            (new Rune(0x1a60), new Rune(0x1a7c), RuneCategory.Extend),
            (new Rune(0x1a7f), new Rune(0x1a7f), RuneCategory.Extend),
            (new Rune(0x1a80), new Rune(0x1a89), RuneCategory.Numeric),
            (new Rune(0x1a90), new Rune(0x1a99), RuneCategory.Numeric),
            (new Rune(0x1ab0), new Rune(0x1ac0), RuneCategory.Extend),
            (new Rune(0x1b00), new Rune(0x1b04), RuneCategory.Extend),
            (new Rune(0x1b05), new Rune(0x1b33), RuneCategory.ALetter),
            (new Rune(0x1b34), new Rune(0x1b44), RuneCategory.Extend),
            (new Rune(0x1b45), new Rune(0x1b4b), RuneCategory.ALetter),
            (new Rune(0x1b50), new Rune(0x1b59), RuneCategory.Numeric),
            (new Rune(0x1b6b), new Rune(0x1b73), RuneCategory.Extend),
            (new Rune(0x1b80), new Rune(0x1b82), RuneCategory.Extend),
            (new Rune(0x1b83), new Rune(0x1ba0), RuneCategory.ALetter),
            (new Rune(0x1ba1), new Rune(0x1bad), RuneCategory.Extend),
            (new Rune(0x1bae), new Rune(0x1baf), RuneCategory.ALetter),
            (new Rune(0x1bb0), new Rune(0x1bb9), RuneCategory.Numeric),
            (new Rune(0x1bba), new Rune(0x1be5), RuneCategory.ALetter),
            (new Rune(0x1be6), new Rune(0x1bf3), RuneCategory.Extend),
            (new Rune(0x1c00), new Rune(0x1c23), RuneCategory.ALetter),
            (new Rune(0x1c24), new Rune(0x1c37), RuneCategory.Extend),
            (new Rune(0x1c40), new Rune(0x1c49), RuneCategory.Numeric),
            (new Rune(0x1c4d), new Rune(0x1c4f), RuneCategory.ALetter),
            (new Rune(0x1c50), new Rune(0x1c59), RuneCategory.Numeric),
            (new Rune(0x1c5a), new Rune(0x1c7d), RuneCategory.ALetter),
            (new Rune(0x1c80), new Rune(0x1c88), RuneCategory.ALetter),
            (new Rune(0x1c90), new Rune(0x1cba), RuneCategory.ALetter),
            (new Rune(0x1cbd), new Rune(0x1cbf), RuneCategory.ALetter),
            (new Rune(0x1cd0), new Rune(0x1cd2), RuneCategory.Extend),
            (new Rune(0x1cd4), new Rune(0x1ce8), RuneCategory.Extend),
            (new Rune(0x1ce9), new Rune(0x1cec), RuneCategory.ALetter),
            (new Rune(0x1ced), new Rune(0x1ced), RuneCategory.Extend),
            (new Rune(0x1cee), new Rune(0x1cf3), RuneCategory.ALetter),
            (new Rune(0x1cf4), new Rune(0x1cf4), RuneCategory.Extend),
            (new Rune(0x1cf5), new Rune(0x1cf6), RuneCategory.ALetter),
            (new Rune(0x1cf7), new Rune(0x1cf9), RuneCategory.Extend),
            (new Rune(0x1cfa), new Rune(0x1cfa), RuneCategory.ALetter),
            (new Rune(0x1d00), new Rune(0x1dbf), RuneCategory.ALetter),
            (new Rune(0x1dc0), new Rune(0x1df9), RuneCategory.Extend),
            (new Rune(0x1dfb), new Rune(0x1dff), RuneCategory.Extend),
            (new Rune(0x1e00), new Rune(0x1f15), RuneCategory.ALetter),
            (new Rune(0x1f18), new Rune(0x1f1d), RuneCategory.ALetter),
            (new Rune(0x1f20), new Rune(0x1f45), RuneCategory.ALetter),
            (new Rune(0x1f48), new Rune(0x1f4d), RuneCategory.ALetter),
            (new Rune(0x1f50), new Rune(0x1f57), RuneCategory.ALetter),
            (new Rune(0x1f59), new Rune(0x1f59), RuneCategory.ALetter),
            (new Rune(0x1f5b), new Rune(0x1f5b), RuneCategory.ALetter),
            (new Rune(0x1f5d), new Rune(0x1f5d), RuneCategory.ALetter),
            (new Rune(0x1f5f), new Rune(0x1f7d), RuneCategory.ALetter),
            (new Rune(0x1f80), new Rune(0x1fb4), RuneCategory.ALetter),
            (new Rune(0x1fb6), new Rune(0x1fbc), RuneCategory.ALetter),
            (new Rune(0x1fbe), new Rune(0x1fbe), RuneCategory.ALetter),
            (new Rune(0x1fc2), new Rune(0x1fc4),RuneCategory.ALetter),
            (new Rune(0x1fc6), new Rune(0x1fcc), RuneCategory.ALetter),
            (new Rune(0x1fd0), new Rune(0x1fd3), RuneCategory.ALetter),
            (new Rune(0x1fd6), new Rune(0x1fdb), RuneCategory.ALetter),
            (new Rune(0x1fe0), new Rune(0x1fec), RuneCategory.ALetter),
            (new Rune(0x1ff2), new Rune(0x1ff4), RuneCategory.ALetter),
            (new Rune(0x1ff6), new Rune(0x1ffc), RuneCategory.ALetter),
            (new Rune(0x2000), new Rune(0x2006), RuneCategory.WSegSpace),
            (new Rune(0x2008), new Rune(0x200a), RuneCategory.WSegSpace),
            (new Rune(0x200c), new Rune(0x200c), RuneCategory.Extend),
            (new Rune(0x200d), new Rune(0x200d), RuneCategory.Zwj),
            (new Rune(0x200e), new Rune(0x200f), RuneCategory.Format),
            (new Rune(0x2018), new Rune(0x2019), RuneCategory.MidNumLet),
            (new Rune(0x2024), new Rune(0x2024), RuneCategory.MidNumLet),
            (new Rune(0x2027), new Rune(0x2027), RuneCategory.MidLetter),
            (new Rune(0x2028), new Rune(0x2029), RuneCategory.Newline),
            (new Rune(0x202a), new Rune(0x202e), RuneCategory.Format),
            (new Rune(0x202f), new Rune(0x202f), RuneCategory.ExtendNumLet),
            (new Rune(0x203f), new Rune(0x2040), RuneCategory.ExtendNumLet),
            (new Rune(0x2044), new Rune(0x2044), RuneCategory.MidNum),
            (new Rune(0x2054), new Rune(0x2054), RuneCategory.ExtendNumLet),
            (new Rune(0x205f), new Rune(0x205f), RuneCategory.WSegSpace),
            (new Rune(0x2060), new Rune(0x2064), RuneCategory.Format),
            (new Rune(0x2066), new Rune(0x206f), RuneCategory.Format),
            (new Rune(0x2071), new Rune(0x2071), RuneCategory.ALetter),
            (new Rune(0x207f), new Rune(0x207f), RuneCategory.ALetter),
            (new Rune(0x2090), new Rune(0x209c), RuneCategory.ALetter),
            (new Rune(0x20d0), new Rune(0x20f0), RuneCategory.Extend),
            (new Rune(0x2102), new Rune(0x2102), RuneCategory.ALetter),
            (new Rune(0x2107), new Rune(0x2107), RuneCategory.ALetter),
            (new Rune(0x210a), new Rune(0x2113), RuneCategory.ALetter),
            (new Rune(0x2115), new Rune(0x2115), RuneCategory.ALetter),
            (new Rune(0x2119), new Rune(0x211d), RuneCategory.ALetter),
            (new Rune(0x2124), new Rune(0x2124), RuneCategory.ALetter),
            (new Rune(0x2126), new Rune(0x2126), RuneCategory.ALetter),
            (new Rune(0x2128), new Rune(0x2128), RuneCategory.ALetter),
            (new Rune(0x212a), new Rune(0x212d), RuneCategory.ALetter),
            (new Rune(0x212f), new Rune(0x2139), RuneCategory.ALetter),
            (new Rune(0x213c), new Rune(0x213f), RuneCategory.ALetter),
            (new Rune(0x2145), new Rune(0x2149), RuneCategory.ALetter),
            (new Rune(0x214e), new Rune(0x214e), RuneCategory.ALetter),
            (new Rune(0x2160), new Rune(0x2188), RuneCategory.ALetter),
            (new Rune(0x24b6), new Rune(0x24e9), RuneCategory.ALetter),
            (new Rune(0x2c00), new Rune(0x2c2e), RuneCategory.ALetter),
            (new Rune(0x2c30), new Rune(0x2c5e), RuneCategory.ALetter),
            (new Rune(0x2c60), new Rune(0x2ce4), RuneCategory.ALetter),
            (new Rune(0x2ceb), new Rune(0x2cee), RuneCategory.ALetter),
            (new Rune(0x2cef), new Rune(0x2cf1), RuneCategory.Extend),
            (new Rune(0x2cf2), new Rune(0x2cf3), RuneCategory.ALetter),
            (new Rune(0x2d00), new Rune(0x2d25), RuneCategory.ALetter),
            (new Rune(0x2d27), new Rune(0x2d27), RuneCategory.ALetter),
            (new Rune(0x2d2d), new Rune(0x2d2d), RuneCategory.ALetter),
            (new Rune(0x2d30), new Rune(0x2d67), RuneCategory.ALetter),
            (new Rune(0x2d6f), new Rune(0x2d6f), RuneCategory.ALetter),
            (new Rune(0x2d7f), new Rune(0x2d7f), RuneCategory.Extend),
            (new Rune(0x2d80), new Rune(0x2d96), RuneCategory.ALetter),
            (new Rune(0x2da0), new Rune(0x2da6), RuneCategory.ALetter),
            (new Rune(0x2da8), new Rune(0x2dae), RuneCategory.ALetter),
            (new Rune(0x2db0), new Rune(0x2db6), RuneCategory.ALetter),
            (new Rune(0x2db8), new Rune(0x2dbe), RuneCategory.ALetter),
            (new Rune(0x2dc0), new Rune(0x2dc6), RuneCategory.ALetter),
            (new Rune(0x2dc8), new Rune(0x2dce), RuneCategory.ALetter),
            (new Rune(0x2dd0), new Rune(0x2dd6), RuneCategory.ALetter),
            (new Rune(0x2dd8), new Rune(0x2dde), RuneCategory.ALetter),
            (new Rune(0x2de0), new Rune(0x2dff), RuneCategory.Extend),
            (new Rune(0x2e2f), new Rune(0x2e2f), RuneCategory.ALetter),
            (new Rune(0x3000), new Rune(0x3000), RuneCategory.WSegSpace),
            (new Rune(0x3005), new Rune(0x3005), RuneCategory.ALetter),
            (new Rune(0x302a), new Rune(0x302f), RuneCategory.Extend),
            (new Rune(0x3031), new Rune(0x3035), RuneCategory.Katakana),
            (new Rune(0x303b), new Rune(0x303c), RuneCategory.ALetter),
            (new Rune(0x3099), new Rune(0x309a), RuneCategory.Extend),
            (new Rune(0x309b), new Rune(0x309c), RuneCategory.Katakana),
            (new Rune(0x30a0), new Rune(0x30fa), RuneCategory.Katakana),
            (new Rune(0x30fc), new Rune(0x30ff), RuneCategory.Katakana),
            (new Rune(0x3105), new Rune(0x312f), RuneCategory.ALetter),
            (new Rune(0x3131), new Rune(0x318e), RuneCategory.ALetter),
            (new Rune(0x31a0), new Rune(0x31bf), RuneCategory.ALetter),
            (new Rune(0x31f0), new Rune(0x31ff), RuneCategory.Katakana),
            (new Rune(0x32d0), new Rune(0x32fe), RuneCategory.Katakana),
            (new Rune(0x3300), new Rune(0x3357), RuneCategory.Katakana),
            (new Rune(0xa000), new Rune(0xa48c), RuneCategory.ALetter),
            (new Rune(0xa4d0), new Rune(0xa4fd), RuneCategory.ALetter),
            (new Rune(0xa500), new Rune(0xa60c), RuneCategory.ALetter),
            (new Rune(0xa610), new Rune(0xa61f), RuneCategory.ALetter),
            (new Rune(0xa620), new Rune(0xa629), RuneCategory.Numeric),
            (new Rune(0xa62a), new Rune(0xa62b), RuneCategory.ALetter),
            (new Rune(0xa640), new Rune(0xa66e), RuneCategory.ALetter),
            (new Rune(0xa66f), new Rune(0xa672), RuneCategory.Extend),
            (new Rune(0xa674), new Rune(0xa67d), RuneCategory.Extend),
            (new Rune(0xa67f), new Rune(0xa69d), RuneCategory.ALetter),
            (new Rune(0xa69e), new Rune(0xa69f), RuneCategory.Extend),
            (new Rune(0xa6a0), new Rune(0xa6ef), RuneCategory.ALetter),
            (new Rune(0xa6f0), new Rune(0xa6f1), RuneCategory.Extend),
            (new Rune(0xa708), new Rune(0xa7bf), RuneCategory.ALetter),
            (new Rune(0xa7c2), new Rune(0xa7ca), RuneCategory.ALetter),
            (new Rune(0xa7f5), new Rune(0xa801), RuneCategory.ALetter),
            (new Rune(0xa802), new Rune(0xa802), RuneCategory.Extend),
            (new Rune(0xa803), new Rune(0xa805), RuneCategory.ALetter),
            (new Rune(0xa806), new Rune(0xa806), RuneCategory.Extend),
            (new Rune(0xa807), new Rune(0xa80a), RuneCategory.ALetter),
            (new Rune(0xa80b), new Rune(0xa80b), RuneCategory.Extend),
            (new Rune(0xa80c), new Rune(0xa822), RuneCategory.ALetter),
            (new Rune(0xa823), new Rune(0xa827), RuneCategory.Extend),
            (new Rune(0xa82c), new Rune(0xa82c), RuneCategory.Extend),
            (new Rune(0xa840), new Rune(0xa873), RuneCategory.ALetter),
            (new Rune(0xa880), new Rune(0xa881), RuneCategory.Extend),
            (new Rune(0xa882), new Rune(0xa8b3), RuneCategory.ALetter),
            (new Rune(0xa8b4), new Rune(0xa8c5), RuneCategory.Extend),
            (new Rune(0xa8d0), new Rune(0xa8d9), RuneCategory.Numeric),
            (new Rune(0xa8e0), new Rune(0xa8f1), RuneCategory.Extend),
            (new Rune(0xa8f2), new Rune(0xa8f7), RuneCategory.ALetter),
            (new Rune(0xa8fb), new Rune(0xa8fb), RuneCategory.ALetter),
            (new Rune(0xa8fd), new Rune(0xa8fe), RuneCategory.ALetter),
            (new Rune(0xa8ff), new Rune(0xa8ff), RuneCategory.Extend),
            (new Rune(0xa900), new Rune(0xa909), RuneCategory.Numeric),
            (new Rune(0xa90a), new Rune(0xa925), RuneCategory.ALetter),
            (new Rune(0xa926), new Rune(0xa92d), RuneCategory.Extend),
            (new Rune(0xa930), new Rune(0xa946), RuneCategory.ALetter),
            (new Rune(0xa947), new Rune(0xa953), RuneCategory.Extend),
            (new Rune(0xa960), new Rune(0xa97c), RuneCategory.ALetter),
            (new Rune(0xa980), new Rune(0xa983), RuneCategory.Extend),
            (new Rune(0xa984), new Rune(0xa9b2), RuneCategory.ALetter),
            (new Rune(0xa9b3), new Rune(0xa9c0), RuneCategory.Extend),
            (new Rune(0xa9cf), new Rune(0xa9cf), RuneCategory.ALetter),
            (new Rune(0xa9d0), new Rune(0xa9d9), RuneCategory.Numeric),
            (new Rune(0xa9e5), new Rune(0xa9e5), RuneCategory.Extend),
            (new Rune(0xa9f0), new Rune(0xa9f9), RuneCategory.Numeric),
            (new Rune(0xaa00), new Rune(0xaa28), RuneCategory.ALetter),
            (new Rune(0xaa29), new Rune(0xaa36), RuneCategory.Extend),
            (new Rune(0xaa40), new Rune(0xaa42), RuneCategory.ALetter),
            (new Rune(0xaa43), new Rune(0xaa43), RuneCategory.Extend),
            (new Rune(0xaa44), new Rune(0xaa4b), RuneCategory.ALetter),
            (new Rune(0xaa4c), new Rune(0xaa4d), RuneCategory.Extend),
            (new Rune(0xaa50), new Rune(0xaa59), RuneCategory.Numeric),
            (new Rune(0xaa7b), new Rune(0xaa7d), RuneCategory.Extend),
            (new Rune(0xaab0), new Rune(0xaab0), RuneCategory.Extend),
            (new Rune(0xaab2), new Rune(0xaab4), RuneCategory.Extend),
            (new Rune(0xaab7), new Rune(0xaab8), RuneCategory.Extend),
            (new Rune(0xaabe), new Rune(0xaabf), RuneCategory.Extend),
            (new Rune(0xaac1), new Rune(0xaac1), RuneCategory.Extend),
            (new Rune(0xaae0), new Rune(0xaaea), RuneCategory.ALetter),
            (new Rune(0xaaeb), new Rune(0xaaef), RuneCategory.Extend),
            (new Rune(0xaaf2), new Rune(0xaaf4), RuneCategory.ALetter),
            (new Rune(0xaaf5), new Rune(0xaaf6), RuneCategory.Extend),
            (new Rune(0xab01), new Rune(0xab06), RuneCategory.ALetter),
            (new Rune(0xab09), new Rune(0xab0e), RuneCategory.ALetter),
            (new Rune(0xab11), new Rune(0xab16), RuneCategory.ALetter),
            (new Rune(0xab20), new Rune(0xab26), RuneCategory.ALetter),
            (new Rune(0xab28), new Rune(0xab2e), RuneCategory.ALetter),
            (new Rune(0xab30), new Rune(0xab69), RuneCategory.ALetter),
            (new Rune(0xab70), new Rune(0xabe2), RuneCategory.ALetter),
            (new Rune(0xabe3), new Rune(0xabea), RuneCategory.Extend),
            (new Rune(0xabec), new Rune(0xabed), RuneCategory.Extend),
            (new Rune(0xabf0), new Rune(0xabf9), RuneCategory.Numeric),
            (new Rune(0xac00), new Rune(0xd7a3), RuneCategory.ALetter),
            (new Rune(0xd7b0), new Rune(0xd7c6), RuneCategory.ALetter),
            (new Rune(0xd7cb), new Rune(0xd7fb), RuneCategory.ALetter),
            (new Rune(0xfb00), new Rune(0xfb06), RuneCategory.ALetter),
            (new Rune(0xfb13), new Rune(0xfb17), RuneCategory.ALetter),
            (new Rune(0xfb1d), new Rune(0xfb1d), RuneCategory.HLetter),
            (new Rune(0xfb1e), new Rune(0xfb1e), RuneCategory.Extend),
            (new Rune(0xfb1f), new Rune(0xfb28), RuneCategory.HLetter),
            (new Rune(0xfb2a), new Rune(0xfb36), RuneCategory.HLetter),
            (new Rune(0xfb38), new Rune(0xfb3c), RuneCategory.HLetter),
            (new Rune(0xfb3e), new Rune(0xfb3e), RuneCategory.HLetter),
            (new Rune(0xfb40), new Rune(0xfb41), RuneCategory.HLetter),
            (new Rune(0xfb43), new Rune(0xfb44), RuneCategory.HLetter),
            (new Rune(0xfb46), new Rune(0xfb4f), RuneCategory.HLetter),
            (new Rune(0xfb50), new Rune(0xfbb1), RuneCategory.ALetter),
            (new Rune(0xfbd3), new Rune(0xfd3d), RuneCategory.ALetter),
            (new Rune(0xfd50), new Rune(0xfd8f), RuneCategory.ALetter),
            (new Rune(0xfd92), new Rune(0xfdc7), RuneCategory.ALetter),
            (new Rune(0xfdf0), new Rune(0xfdfb), RuneCategory.ALetter),
            (new Rune(0xfe00), new Rune(0xfe0f), RuneCategory.Extend),
            (new Rune(0xfe10), new Rune(0xfe10), RuneCategory.MidNum),
            (new Rune(0xfe13), new Rune(0xfe13), RuneCategory.MidLetter),
            (new Rune(0xfe14), new Rune(0xfe14), RuneCategory.MidNum),
            (new Rune(0xfe20), new Rune(0xfe2f), RuneCategory.Extend),
            (new Rune(0xfe33), new Rune(0xfe34), RuneCategory.ExtendNumLet),
            (new Rune(0xfe4d), new Rune(0xfe4f), RuneCategory.ExtendNumLet),
            (new Rune(0xfe50), new Rune(0xfe50), RuneCategory.MidNum),
            (new Rune(0xfe52), new Rune(0xfe52), RuneCategory.MidNumLet),
            (new Rune(0xfe54), new Rune(0xfe54), RuneCategory.MidNum),
            (new Rune(0xfe55), new Rune(0xfe55), RuneCategory.MidLetter),
            (new Rune(0xfe70), new Rune(0xfe74), RuneCategory.ALetter),
            (new Rune(0xfe76), new Rune(0xfefc), RuneCategory.ALetter),
            (new Rune(0xfeff), new Rune(0xfeff), RuneCategory.Format),
            (new Rune(0xff07), new Rune(0xff07), RuneCategory.MidNumLet),
            (new Rune(0xff0c), new Rune(0xff0c), RuneCategory.MidNum),
            (new Rune(0xff0e), new Rune(0xff0e), RuneCategory.MidNumLet),
            (new Rune(0xff10), new Rune(0xff19), RuneCategory.Numeric),
            (new Rune(0xff1a), new Rune(0xff1a), RuneCategory.MidLetter),
            (new Rune(0xff1b), new Rune(0xff1b), RuneCategory.MidNum),
            (new Rune(0xff21), new Rune(0xff3a), RuneCategory.ALetter),
            (new Rune(0xff3f), new Rune(0xff3f), RuneCategory.ExtendNumLet),
            (new Rune(0xff41), new Rune(0xff5a), RuneCategory.ALetter),
            (new Rune(0xff66), new Rune(0xff9d), RuneCategory.Katakana),
            (new Rune(0xff9e), new Rune(0xff9f), RuneCategory.Extend),
            (new Rune(0xffa0), new Rune(0xffbe), RuneCategory.ALetter),
            (new Rune(0xffc2), new Rune(0xffc7), RuneCategory.ALetter),
            (new Rune(0xffca), new Rune(0xffcf), RuneCategory.ALetter),
            (new Rune(0xffd2), new Rune(0xffd7), RuneCategory.ALetter),
            (new Rune(0xffda), new Rune(0xffdc), RuneCategory.ALetter),
            (new Rune(0xfff9), new Rune(0xfffb), RuneCategory.Format),
            (new Rune(0x10000), new Rune(0x1000b), RuneCategory.ALetter),
            (new Rune(0x1000d), new Rune(0x10026), RuneCategory.ALetter),
            (new Rune(0x10028), new Rune(0x1003a), RuneCategory.ALetter),
            (new Rune(0x1003c), new Rune(0x1003d), RuneCategory.ALetter),
            (new Rune(0x1003f), new Rune(0x1004d), RuneCategory.ALetter),
            (new Rune(0x10050), new Rune(0x1005d), RuneCategory.ALetter),
            (new Rune(0x10080), new Rune(0x100fa), RuneCategory.ALetter),
            (new Rune(0x10140), new Rune(0x10174), RuneCategory.ALetter),
            (new Rune(0x101fd), new Rune(0x101fd), RuneCategory.Extend),
            (new Rune(0x10280), new Rune(0x1029c), RuneCategory.ALetter),
            (new Rune(0x102a0), new Rune(0x102d0), RuneCategory.ALetter),
            (new Rune(0x102e0), new Rune(0x102e0), RuneCategory.Extend),
            (new Rune(0x10300), new Rune(0x1031f), RuneCategory.ALetter),
            (new Rune(0x1032d), new Rune(0x1034a), RuneCategory.ALetter),
            (new Rune(0x10350), new Rune(0x10375), RuneCategory.ALetter),
            (new Rune(0x10376), new Rune(0x1037a), RuneCategory.Extend),
            (new Rune(0x10380), new Rune(0x1039d), RuneCategory.ALetter),
            (new Rune(0x103a0), new Rune(0x103c3), RuneCategory.ALetter),
            (new Rune(0x103c8), new Rune(0x103cf), RuneCategory.ALetter),
            (new Rune(0x103d1), new Rune(0x103d5), RuneCategory.ALetter),
            (new Rune(0x10400), new Rune(0x1049d), RuneCategory.ALetter),
            (new Rune(0x104a0), new Rune(0x104a9), RuneCategory.Numeric),
            (new Rune(0x104b0), new Rune(0x104d3), RuneCategory.ALetter),
            (new Rune(0x104d8), new Rune(0x104fb), RuneCategory.ALetter),
            (new Rune(0x10500), new Rune(0x10527), RuneCategory.ALetter),
            (new Rune(0x10530), new Rune(0x10563), RuneCategory.ALetter),
            (new Rune(0x10600), new Rune(0x10736), RuneCategory.ALetter),
            (new Rune(0x10740), new Rune(0x10755), RuneCategory.ALetter),
            (new Rune(0x10760), new Rune(0x10767), RuneCategory.ALetter),
            (new Rune(0x10800), new Rune(0x10805), RuneCategory.ALetter),
            (new Rune(0x10808), new Rune(0x10808), RuneCategory.ALetter),
            (new Rune(0x1080a), new Rune(0x10835), RuneCategory.ALetter),
            (new Rune(0x10837), new Rune(0x10838), RuneCategory.ALetter),
            (new Rune(0x1083c), new Rune(0x1083c), RuneCategory.ALetter),
            (new Rune(0x1083f), new Rune(0x10855), RuneCategory.ALetter),
            (new Rune(0x10860), new Rune(0x10876), RuneCategory.ALetter),
            (new Rune(0x10880), new Rune(0x1089e), RuneCategory.ALetter),
            (new Rune(0x108e0), new Rune(0x108f2), RuneCategory.ALetter),
            (new Rune(0x108f4), new Rune(0x108f5), RuneCategory.ALetter),
            (new Rune(0x10900), new Rune(0x10915), RuneCategory.ALetter),
            (new Rune(0x10920), new Rune(0x10939), RuneCategory.ALetter),
            (new Rune(0x10980), new Rune(0x109b7), RuneCategory.ALetter),
            (new Rune(0x109be), new Rune(0x109bf), RuneCategory.ALetter),
            (new Rune(0x10a00), new Rune(0x10a00), RuneCategory.ALetter),
            (new Rune(0x10a01), new Rune(0x10a03), RuneCategory.Extend),
            (new Rune(0x10a05), new Rune(0x10a06), RuneCategory.Extend),
            (new Rune(0x10a0c), new Rune(0x10a0f), RuneCategory.Extend),
            (new Rune(0x10a10), new Rune(0x10a13), RuneCategory.ALetter),
            (new Rune(0x10a15), new Rune(0x10a17), RuneCategory.ALetter),
            (new Rune(0x10a19), new Rune(0x10a35), RuneCategory.ALetter),
            (new Rune(0x10a38), new Rune(0x10a3a), RuneCategory.Extend),
            (new Rune(0x10a3f), new Rune(0x10a3f), RuneCategory.Extend),
            (new Rune(0x10a60), new Rune(0x10a7c), RuneCategory.ALetter),
            (new Rune(0x10a80), new Rune(0x10a9c), RuneCategory.ALetter),
            (new Rune(0x10ac0), new Rune(0x10ac7), RuneCategory.ALetter),
            (new Rune(0x10ac9), new Rune(0x10ae4), RuneCategory.ALetter),
            (new Rune(0x10ae5), new Rune(0x10ae6), RuneCategory.Extend),
            (new Rune(0x10b00), new Rune(0x10b35), RuneCategory.ALetter),
            (new Rune(0x10b40), new Rune(0x10b55), RuneCategory.ALetter),
            (new Rune(0x10b60), new Rune(0x10b72), RuneCategory.ALetter),
            (new Rune(0x10b80), new Rune(0x10b91), RuneCategory.ALetter),
            (new Rune(0x10c00), new Rune(0x10c48), RuneCategory.ALetter),
            (new Rune(0x10c80), new Rune(0x10cb2), RuneCategory.ALetter),
            (new Rune(0x10cc0), new Rune(0x10cf2), RuneCategory.ALetter),
            (new Rune(0x10d00), new Rune(0x10d23), RuneCategory.ALetter),
            (new Rune(0x10d24), new Rune(0x10d27), RuneCategory.Extend),
            (new Rune(0x10d30), new Rune(0x10d39), RuneCategory.Numeric),
            (new Rune(0x10e80), new Rune(0x10ea9), RuneCategory.ALetter),
            (new Rune(0x10eab), new Rune(0x10eac), RuneCategory.Extend),
            (new Rune(0x10eb0), new Rune(0x10eb1), RuneCategory.ALetter),
            (new Rune(0x10f00), new Rune(0x10f1c), RuneCategory.ALetter),
            (new Rune(0x10f27), new Rune(0x10f27), RuneCategory.ALetter),
            (new Rune(0x10f30), new Rune(0x10f45), RuneCategory.ALetter),
            (new Rune(0x10f46), new Rune(0x10f50), RuneCategory.Extend),
            (new Rune(0x10fb0), new Rune(0x10fc4), RuneCategory.ALetter),
            (new Rune(0x10fe0), new Rune(0x10ff6), RuneCategory.ALetter),
            (new Rune(0x11000), new Rune(0x11002), RuneCategory.Extend),
            (new Rune(0x11003), new Rune(0x11037), RuneCategory.ALetter),
            (new Rune(0x11038), new Rune(0x11046), RuneCategory.Extend),
            (new Rune(0x11066), new Rune(0x1106f), RuneCategory.Numeric),
            (new Rune(0x1107f), new Rune(0x11082), RuneCategory.Extend),
            (new Rune(0x11083), new Rune(0x110af), RuneCategory.ALetter),
            (new Rune(0x110b0), new Rune(0x110ba), RuneCategory.Extend),
            (new Rune(0x110bd), new Rune(0x110bd), RuneCategory.Format),
            (new Rune(0x110cd), new Rune(0x110cd), RuneCategory.Format),
            (new Rune(0x110d0), new Rune(0x110e8), RuneCategory.ALetter),
            (new Rune(0x110f0), new Rune(0x110f9), RuneCategory.Numeric),
            (new Rune(0x11100), new Rune(0x11102), RuneCategory.Extend),
            (new Rune(0x11103), new Rune(0x11126), RuneCategory.ALetter),
            (new Rune(0x11127), new Rune(0x11134), RuneCategory.Extend),
            (new Rune(0x11136), new Rune(0x1113f), RuneCategory.Numeric),
            (new Rune(0x11144), new Rune(0x11144), RuneCategory.ALetter),
            (new Rune(0x11145), new Rune(0x11146), RuneCategory.Extend),
            (new Rune(0x11147), new Rune(0x11147), RuneCategory.ALetter),
            (new Rune(0x11150), new Rune(0x11172), RuneCategory.ALetter),
            (new Rune(0x11173), new Rune(0x11173), RuneCategory.Extend),
            (new Rune(0x11176), new Rune(0x11176), RuneCategory.ALetter),
            (new Rune(0x11180), new Rune(0x11182), RuneCategory.Extend),
            (new Rune(0x11183), new Rune(0x111b2), RuneCategory.ALetter),
            (new Rune(0x111b3), new Rune(0x111c0), RuneCategory.Extend),
            (new Rune(0x111c1), new Rune(0x111c4), RuneCategory.ALetter),
            (new Rune(0x111c9), new Rune(0x111cc), RuneCategory.Extend),
            (new Rune(0x111ce), new Rune(0x111cf), RuneCategory.Extend),
            (new Rune(0x111d0), new Rune(0x111d9), RuneCategory.Numeric),
            (new Rune(0x111da), new Rune(0x111da), RuneCategory.ALetter),
            (new Rune(0x111dc), new Rune(0x111dc), RuneCategory.ALetter),
            (new Rune(0x11200), new Rune(0x11211), RuneCategory.ALetter),
            (new Rune(0x11213), new Rune(0x1122b), RuneCategory.ALetter),
            (new Rune(0x1122c), new Rune(0x11237), RuneCategory.Extend),
            (new Rune(0x1123e), new Rune(0x1123e), RuneCategory.Extend),
            (new Rune(0x11280), new Rune(0x11286), RuneCategory.ALetter),
            (new Rune(0x11288), new Rune(0x11288), RuneCategory.ALetter),
            (new Rune(0x1128a), new Rune(0x1128d), RuneCategory.ALetter),
            (new Rune(0x1128f), new Rune(0x1129d), RuneCategory.ALetter),
            (new Rune(0x1129f), new Rune(0x112a8), RuneCategory.ALetter),
            (new Rune(0x112b0), new Rune(0x112de), RuneCategory.ALetter),
            (new Rune(0x112df), new Rune(0x112ea), RuneCategory.Extend),
            (new Rune(0x112f0), new Rune(0x112f9), RuneCategory.Numeric),
            (new Rune(0x11300), new Rune(0x11303), RuneCategory.Extend),
            (new Rune(0x11305), new Rune(0x1130c), RuneCategory.ALetter),
            (new Rune(0x1130f), new Rune(0x11310), RuneCategory.ALetter),
            (new Rune(0x11313), new Rune(0x11328), RuneCategory.ALetter),
            (new Rune(0x1132a), new Rune(0x11330), RuneCategory.ALetter),
            (new Rune(0x11332), new Rune(0x11333), RuneCategory.ALetter),
            (new Rune(0x11335), new Rune(0x11339), RuneCategory.ALetter),
            (new Rune(0x1133b), new Rune(0x1133c), RuneCategory.Extend),
            (new Rune(0x1133d), new Rune(0x1133d), RuneCategory.ALetter),
            (new Rune(0x1133e), new Rune(0x11344), RuneCategory.Extend),
            (new Rune(0x11347), new Rune(0x11348), RuneCategory.Extend),
            (new Rune(0x1134b), new Rune(0x1134d), RuneCategory.Extend),
            (new Rune(0x11350), new Rune(0x11350), RuneCategory.ALetter),
            (new Rune(0x11357), new Rune(0x11357), RuneCategory.Extend),
            (new Rune(0x1135d), new Rune(0x11361), RuneCategory.ALetter),
            (new Rune(0x11362), new Rune(0x11363), RuneCategory.Extend),
            (new Rune(0x11366), new Rune(0x1136c), RuneCategory.Extend),
            (new Rune(0x11370), new Rune(0x11374), RuneCategory.Extend),
            (new Rune(0x11400), new Rune(0x11434), RuneCategory.ALetter),
            (new Rune(0x11435), new Rune(0x11446), RuneCategory.Extend),
            (new Rune(0x11447), new Rune(0x1144a), RuneCategory.ALetter),
            (new Rune(0x11450), new Rune(0x11459), RuneCategory.Numeric),
            (new Rune(0x1145e), new Rune(0x1145e), RuneCategory.Extend),
            (new Rune(0x1145f), new Rune(0x11461), RuneCategory.ALetter),
            (new Rune(0x11480), new Rune(0x114af), RuneCategory.ALetter),
            (new Rune(0x114b0), new Rune(0x114c3), RuneCategory.Extend),
            (new Rune(0x114c4), new Rune(0x114c5), RuneCategory.ALetter),
            (new Rune(0x114c7), new Rune(0x114c7), RuneCategory.ALetter),
            (new Rune(0x114d0), new Rune(0x114d9), RuneCategory.Numeric),
            (new Rune(0x11580), new Rune(0x115ae), RuneCategory.ALetter),
            (new Rune(0x115af), new Rune(0x115b5), RuneCategory.Extend),
            (new Rune(0x115b8), new Rune(0x115c0), RuneCategory.Extend),
            (new Rune(0x115d8), new Rune(0x115db), RuneCategory.ALetter),
            (new Rune(0x115dc), new Rune(0x115dd), RuneCategory.Extend),
            (new Rune(0x11600), new Rune(0x1162f), RuneCategory.ALetter),
            (new Rune(0x11630), new Rune(0x11640), RuneCategory.Extend),
            (new Rune(0x11644), new Rune(0x11644), RuneCategory.ALetter),
            (new Rune(0x11650), new Rune(0x11659), RuneCategory.Numeric),
            (new Rune(0x11680), new Rune(0x116aa), RuneCategory.ALetter),
            (new Rune(0x116ab), new Rune(0x116b7), RuneCategory.Extend),
            (new Rune(0x116b8), new Rune(0x116b8), RuneCategory.ALetter),
            (new Rune(0x116c0), new Rune(0x116c9), RuneCategory.Numeric),
            (new Rune(0x1171d), new Rune(0x1172b), RuneCategory.Extend),
            (new Rune(0x11730), new Rune(0x11739), RuneCategory.Numeric),
            (new Rune(0x11800), new Rune(0x1182b), RuneCategory.ALetter),
            (new Rune(0x1182c), new Rune(0x1183a), RuneCategory.Extend),
            (new Rune(0x118a0), new Rune(0x118df), RuneCategory.ALetter),
            (new Rune(0x118e0), new Rune(0x118e9), RuneCategory.Numeric),
            (new Rune(0x118ff), new Rune(0x11906), RuneCategory.ALetter),
            (new Rune(0x11909), new Rune(0x11909), RuneCategory.ALetter),
            (new Rune(0x1190c), new Rune(0x11913), RuneCategory.ALetter),
            (new Rune(0x11915), new Rune(0x11916), RuneCategory.ALetter),
            (new Rune(0x11918), new Rune(0x1192f), RuneCategory.ALetter),
            (new Rune(0x11930), new Rune(0x11935), RuneCategory.Extend),
            (new Rune(0x11937), new Rune(0x11938), RuneCategory.Extend),
            (new Rune(0x1193b), new Rune(0x1193e), RuneCategory.Extend),
            (new Rune(0x1193f), new Rune(0x1193f), RuneCategory.ALetter),
            (new Rune(0x11940), new Rune(0x11940), RuneCategory.Extend),
            (new Rune(0x11941), new Rune(0x11941), RuneCategory.ALetter),
            (new Rune(0x11942), new Rune(0x11943), RuneCategory.Extend),
            (new Rune(0x11950), new Rune(0x11959), RuneCategory.Numeric),
            (new Rune(0x119a0), new Rune(0x119a7), RuneCategory.ALetter),
            (new Rune(0x119aa), new Rune(0x119d0), RuneCategory.ALetter),
            (new Rune(0x119d1), new Rune(0x119d7), RuneCategory.Extend),
            (new Rune(0x119da), new Rune(0x119e0), RuneCategory.Extend),
            (new Rune(0x119e1), new Rune(0x119e1), RuneCategory.ALetter),
            (new Rune(0x119e3), new Rune(0x119e3), RuneCategory.ALetter),
            (new Rune(0x119e4), new Rune(0x119e4), RuneCategory.Extend),
            (new Rune(0x11a00), new Rune(0x11a00), RuneCategory.ALetter),
            (new Rune(0x11a01), new Rune(0x11a0a), RuneCategory.Extend),
            (new Rune(0x11a0b), new Rune(0x11a32), RuneCategory.ALetter),
            (new Rune(0x11a33), new Rune(0x11a39), RuneCategory.Extend),
            (new Rune(0x11a3a), new Rune(0x11a3a), RuneCategory.ALetter),
            (new Rune(0x11a3b), new Rune(0x11a3e), RuneCategory.Extend),
            (new Rune(0x11a47), new Rune(0x11a47), RuneCategory.Extend),
            (new Rune(0x11a50), new Rune(0x11a50), RuneCategory.ALetter),
            (new Rune(0x11a51), new Rune(0x11a5b), RuneCategory.Extend),
            (new Rune(0x11a5c), new Rune(0x11a89), RuneCategory.ALetter),
            (new Rune(0x11a8a), new Rune(0x11a99), RuneCategory.Extend),
            (new Rune(0x11a9d), new Rune(0x11a9d), RuneCategory.ALetter),
            (new Rune(0x11ac0), new Rune(0x11af8), RuneCategory.ALetter),
            (new Rune(0x11c00), new Rune(0x11c08), RuneCategory.ALetter),
            (new Rune(0x11c0a), new Rune(0x11c2e), RuneCategory.ALetter),
            (new Rune(0x11c2f), new Rune(0x11c36), RuneCategory.Extend),
            (new Rune(0x11c38), new Rune(0x11c3f), RuneCategory.Extend),
            (new Rune(0x11c40), new Rune(0x11c40), RuneCategory.ALetter),
            (new Rune(0x11c50), new Rune(0x11c59), RuneCategory.Numeric),
            (new Rune(0x11c72), new Rune(0x11c8f), RuneCategory.ALetter),
            (new Rune(0x11c92), new Rune(0x11ca7), RuneCategory.Extend),
            (new Rune(0x11ca9), new Rune(0x11cb6), RuneCategory.Extend),
            (new Rune(0x11d00), new Rune(0x11d06), RuneCategory.ALetter),
            (new Rune(0x11d08), new Rune(0x11d09), RuneCategory.ALetter),
            (new Rune(0x11d0b), new Rune(0x11d30), RuneCategory.ALetter),
            (new Rune(0x11d31), new Rune(0x11d36), RuneCategory.Extend),
            (new Rune(0x11d3a), new Rune(0x11d3a), RuneCategory.Extend),
            (new Rune(0x11d3c), new Rune(0x11d3d), RuneCategory.Extend),
            (new Rune(0x11d3f), new Rune(0x11d45), RuneCategory.Extend),
            (new Rune(0x11d46), new Rune(0x11d46), RuneCategory.ALetter),
            (new Rune(0x11d47), new Rune(0x11d47), RuneCategory.Extend),
            (new Rune(0x11d50), new Rune(0x11d59), RuneCategory.Numeric),
            (new Rune(0x11d60), new Rune(0x11d65), RuneCategory.ALetter),
            (new Rune(0x11d67), new Rune(0x11d68), RuneCategory.ALetter),
            (new Rune(0x11d6a), new Rune(0x11d89), RuneCategory.ALetter),
            (new Rune(0x11d8a), new Rune(0x11d8e), RuneCategory.Extend),
            (new Rune(0x11d90), new Rune(0x11d91), RuneCategory.Extend),
            (new Rune(0x11d93), new Rune(0x11d97), RuneCategory.Extend),
            (new Rune(0x11d98), new Rune(0x11d98), RuneCategory.ALetter),
            (new Rune(0x11da0), new Rune(0x11da9), RuneCategory.Numeric),
            (new Rune(0x11ee0), new Rune(0x11ef2), RuneCategory.ALetter),
            (new Rune(0x11ef3), new Rune(0x11ef6), RuneCategory.Extend),
            (new Rune(0x11fb0), new Rune(0x11fb0), RuneCategory.ALetter),
            (new Rune(0x12000), new Rune(0x12399), RuneCategory.ALetter),
            (new Rune(0x12400), new Rune(0x1246e), RuneCategory.ALetter),
            (new Rune(0x12480), new Rune(0x12543), RuneCategory.ALetter),
            (new Rune(0x13000), new Rune(0x1342e), RuneCategory.ALetter),
            (new Rune(0x13430), new Rune(0x13438), RuneCategory.Format),
            (new Rune(0x14400), new Rune(0x14646), RuneCategory.ALetter),
            (new Rune(0x16800), new Rune(0x16a38), RuneCategory.ALetter),
            (new Rune(0x16a40), new Rune(0x16a5e), RuneCategory.ALetter),
            (new Rune(0x16a60), new Rune(0x16a69), RuneCategory.Numeric),
            (new Rune(0x16ad0), new Rune(0x16aed), RuneCategory.ALetter),
            (new Rune(0x16af0), new Rune(0x16af4), RuneCategory.Extend),
            (new Rune(0x16b00), new Rune(0x16b2f), RuneCategory.ALetter),
            (new Rune(0x16b30), new Rune(0x16b36), RuneCategory.Extend),
            (new Rune(0x16b40), new Rune(0x16b43), RuneCategory.ALetter),
            (new Rune(0x16b50), new Rune(0x16b59), RuneCategory.Numeric),
            (new Rune(0x16b63), new Rune(0x16b77), RuneCategory.ALetter),
            (new Rune(0x16b7d), new Rune(0x16b8f), RuneCategory.ALetter),
            (new Rune(0x16e40), new Rune(0x16e7f), RuneCategory.ALetter),
            (new Rune(0x16f00), new Rune(0x16f4a), RuneCategory.ALetter),
            (new Rune(0x16f4f), new Rune(0x16f4f), RuneCategory.Extend),
            (new Rune(0x16f50), new Rune(0x16f50), RuneCategory.ALetter),
            (new Rune(0x16f51), new Rune(0x16f87), RuneCategory.Extend),
            (new Rune(0x16f8f), new Rune(0x16f92), RuneCategory.Extend),
            (new Rune(0x16f93), new Rune(0x16f9f), RuneCategory.ALetter),
            (new Rune(0x16fe0), new Rune(0x16fe1), RuneCategory.ALetter),
            (new Rune(0x16fe3), new Rune(0x16fe3), RuneCategory.ALetter),
            (new Rune(0x16fe4), new Rune(0x16fe4), RuneCategory.Extend),
            (new Rune(0x16ff0), new Rune(0x16ff1), RuneCategory.Extend),
            (new Rune(0x1b000), new Rune(0x1b000), RuneCategory.Katakana),
            (new Rune(0x1b164), new Rune(0x1b167), RuneCategory.Katakana),
            (new Rune(0x1bc00), new Rune(0x1bc6a), RuneCategory.ALetter),
            (new Rune(0x1bc70), new Rune(0x1bc7c), RuneCategory.ALetter),
            (new Rune(0x1bc80), new Rune(0x1bc88), RuneCategory.ALetter),
            (new Rune(0x1bc90), new Rune(0x1bc99), RuneCategory.ALetter),
            (new Rune(0x1bc9d), new Rune(0x1bc9e), RuneCategory.Extend),
            (new Rune(0x1bca0), new Rune(0x1bca3), RuneCategory.Format),
            (new Rune(0x1d165), new Rune(0x1d169), RuneCategory.Extend),
            (new Rune(0x1d16d), new Rune(0x1d172), RuneCategory.Extend),
            (new Rune(0x1d173), new Rune(0x1d17a), RuneCategory.Format),
            (new Rune(0x1d17b), new Rune(0x1d182), RuneCategory.Extend),
            (new Rune(0x1d185), new Rune(0x1d18b), RuneCategory.Extend),
            (new Rune(0x1d1aa), new Rune(0x1d1ad), RuneCategory.Extend),
            (new Rune(0x1d242), new Rune(0x1d244), RuneCategory.Extend),
            (new Rune(0x1d400), new Rune(0x1d454), RuneCategory.ALetter),
            (new Rune(0x1d456), new Rune(0x1d49c), RuneCategory.ALetter),
            (new Rune(0x1d49e), new Rune(0x1d49f), RuneCategory.ALetter),
            (new Rune(0x1d4a2), new Rune(0x1d4a2), RuneCategory.ALetter),
            (new Rune(0x1d4a5), new Rune(0x1d4a6), RuneCategory.ALetter),
            (new Rune(0x1d4a9), new Rune(0x1d4ac), RuneCategory.ALetter),
            (new Rune(0x1d4ae), new Rune(0x1d4b9), RuneCategory.ALetter),
            (new Rune(0x1d4bb), new Rune(0x1d4bb), RuneCategory.ALetter),
            (new Rune(0x1d4bd), new Rune(0x1d4c3), RuneCategory.ALetter),
            (new Rune(0x1d4c5), new Rune(0x1d505), RuneCategory.ALetter),
            (new Rune(0x1d507), new Rune(0x1d50a), RuneCategory.ALetter),
            (new Rune(0x1d50d), new Rune(0x1d514), RuneCategory.ALetter),
            (new Rune(0x1d516), new Rune(0x1d51c), RuneCategory.ALetter),
            (new Rune(0x1d51e), new Rune(0x1d539), RuneCategory.ALetter),
            (new Rune(0x1d53b), new Rune(0x1d53e), RuneCategory.ALetter),
            (new Rune(0x1d540), new Rune(0x1d544), RuneCategory.ALetter),
            (new Rune(0x1d546), new Rune(0x1d546), RuneCategory.ALetter),
            (new Rune(0x1d54a), new Rune(0x1d550), RuneCategory.ALetter),
            (new Rune(0x1d552), new Rune(0x1d6a5), RuneCategory.ALetter),
            (new Rune(0x1d6a8), new Rune(0x1d6c0), RuneCategory.ALetter),
            (new Rune(0x1d6c2), new Rune(0x1d6da), RuneCategory.ALetter),
            (new Rune(0x1d6dc), new Rune(0x1d6fa), RuneCategory.ALetter),
            (new Rune(0x1d6fc), new Rune(0x1d714), RuneCategory.ALetter),
            (new Rune(0x1d716), new Rune(0x1d734), RuneCategory.ALetter),
            (new Rune(0x1d736), new Rune(0x1d74e), RuneCategory.ALetter),
            (new Rune(0x1d750), new Rune(0x1d76e), RuneCategory.ALetter),
            (new Rune(0x1d770), new Rune(0x1d788), RuneCategory.ALetter),
            (new Rune(0x1d78a), new Rune(0x1d7a8), RuneCategory.ALetter),
            (new Rune(0x1d7aa), new Rune(0x1d7c2), RuneCategory.ALetter),
            (new Rune(0x1d7c4), new Rune(0x1d7cb), RuneCategory.ALetter),
            (new Rune(0x1d7ce), new Rune(0x1d7ff), RuneCategory.Numeric),
            (new Rune(0x1da00), new Rune(0x1da36), RuneCategory.Extend),
            (new Rune(0x1da3b), new Rune(0x1da6c), RuneCategory.Extend),
            (new Rune(0x1da75), new Rune(0x1da75), RuneCategory.Extend),
            (new Rune(0x1da84), new Rune(0x1da84), RuneCategory.Extend),
            (new Rune(0x1da9b), new Rune(0x1da9f), RuneCategory.Extend),
            (new Rune(0x1daa1), new Rune(0x1daaf), RuneCategory.Extend),
            (new Rune(0x1e000), new Rune(0x1e006), RuneCategory.Extend),
            (new Rune(0x1e008), new Rune(0x1e018), RuneCategory.Extend),
            (new Rune(0x1e01b), new Rune(0x1e021), RuneCategory.Extend),
            (new Rune(0x1e023), new Rune(0x1e024), RuneCategory.Extend),
            (new Rune(0x1e026), new Rune(0x1e02a), RuneCategory.Extend),
            (new Rune(0x1e100), new Rune(0x1e12c), RuneCategory.ALetter),
            (new Rune(0x1e130), new Rune(0x1e136), RuneCategory.Extend),
            (new Rune(0x1e137), new Rune(0x1e13d), RuneCategory.ALetter),
            (new Rune(0x1e140), new Rune(0x1e149), RuneCategory.Numeric),
            (new Rune(0x1e14e), new Rune(0x1e14e), RuneCategory.ALetter),
            (new Rune(0x1e2c0), new Rune(0x1e2eb), RuneCategory.ALetter),
            (new Rune(0x1e2ec), new Rune(0x1e2ef), RuneCategory.Extend),
            (new Rune(0x1e2f0), new Rune(0x1e2f9), RuneCategory.Numeric),
            (new Rune(0x1e800), new Rune(0x1e8c4), RuneCategory.ALetter),
            (new Rune(0x1e8d0), new Rune(0x1e8d6), RuneCategory.Extend),
            (new Rune(0x1e900), new Rune(0x1e943), RuneCategory.ALetter),
            (new Rune(0x1e944), new Rune(0x1e94a), RuneCategory.Extend),
            (new Rune(0x1e94b), new Rune(0x1e94b), RuneCategory.ALetter),
            (new Rune(0x1e950), new Rune(0x1e959), RuneCategory.Numeric),
            (new Rune(0x1ee00), new Rune(0x1ee03), RuneCategory.ALetter),
            (new Rune(0x1ee05), new Rune(0x1ee1f), RuneCategory.ALetter),
            (new Rune(0x1ee21), new Rune(0x1ee22), RuneCategory.ALetter),
            (new Rune(0x1ee24), new Rune(0x1ee24), RuneCategory.ALetter),
            (new Rune(0x1ee27), new Rune(0x1ee27), RuneCategory.ALetter),
            (new Rune(0x1ee29), new Rune(0x1ee32), RuneCategory.ALetter),
            (new Rune(0x1ee34), new Rune(0x1ee37), RuneCategory.ALetter),
            (new Rune(0x1ee39), new Rune(0x1ee39), RuneCategory.ALetter),
            (new Rune(0x1ee3b), new Rune(0x1ee3b), RuneCategory.ALetter),
            (new Rune(0x1ee42), new Rune(0x1ee42), RuneCategory.ALetter),
            (new Rune(0x1ee47), new Rune(0x1ee47), RuneCategory.ALetter),
            (new Rune(0x1ee49), new Rune(0x1ee49), RuneCategory.ALetter),
            (new Rune(0x1ee4b), new Rune(0x1ee4b), RuneCategory.ALetter),
            (new Rune(0x1ee4d), new Rune(0x1ee4f), RuneCategory.ALetter),
            (new Rune(0x1ee51), new Rune(0x1ee52), RuneCategory.ALetter),
            (new Rune(0x1ee54), new Rune(0x1ee54), RuneCategory.ALetter),
            (new Rune(0x1ee57), new Rune(0x1ee57), RuneCategory.ALetter),
            (new Rune(0x1ee59), new Rune(0x1ee59), RuneCategory.ALetter),
            (new Rune(0x1ee5b), new Rune(0x1ee5b), RuneCategory.ALetter),
            (new Rune(0x1ee5d), new Rune(0x1ee5d), RuneCategory.ALetter),
            (new Rune(0x1ee5f), new Rune(0x1ee5f), RuneCategory.ALetter),
            (new Rune(0x1ee61), new Rune(0x1ee62), RuneCategory.ALetter),
            (new Rune(0x1ee64), new Rune(0x1ee64), RuneCategory.ALetter),
            (new Rune(0x1ee67), new Rune(0x1ee6a), RuneCategory.ALetter),
            (new Rune(0x1ee6c), new Rune(0x1ee72), RuneCategory.ALetter),
            (new Rune(0x1ee74), new Rune(0x1ee77), RuneCategory.ALetter),
            (new Rune(0x1ee79), new Rune(0x1ee7c), RuneCategory.ALetter),
            (new Rune(0x1ee7e), new Rune(0x1ee7e), RuneCategory.ALetter),
            (new Rune(0x1ee80), new Rune(0x1ee89), RuneCategory.ALetter),
            (new Rune(0x1ee8b), new Rune(0x1ee9b), RuneCategory.ALetter),
            (new Rune(0x1eea1), new Rune(0x1eea3), RuneCategory.ALetter),
            (new Rune(0x1eea5), new Rune(0x1eea9), RuneCategory.ALetter),
            (new Rune(0x1eeab), new Rune(0x1eebb), RuneCategory.ALetter),
            (new Rune(0x1f130), new Rune(0x1f149), RuneCategory.ALetter),
            (new Rune(0x1f150), new Rune(0x1f169), RuneCategory.ALetter),
            (new Rune(0x1f170), new Rune(0x1f189), RuneCategory.ALetter),
            (new Rune(0x1f1e6), new Rune(0x1f1ff), RuneCategory.RegionalIndicator),
            (new Rune(0x1f3fb), new Rune(0x1f3ff), RuneCategory.Extend),
            (new Rune(0x1fbf0), new Rune(0x1fbf9), RuneCategory.Numeric),
            (new Rune(0xe0001), new Rune(0xe0001), RuneCategory.Format),
            (new Rune(0xe0020), new Rune(0xe007f), RuneCategory.Extend),
            (new Rune(0xe0100), new Rune(0xe01ef), RuneCategory.Extend)
        };
    }
}
